### ISSUE TITLE
fix: Take z-scale in to factor when slicing

### ISSUE THREAD

**Issue by aytunch** [wolfenrain/sashimi#11]
**Description**

When we scale an object or the world in all 3 directions, the sashimi object only gets scale in x and y axis. It looks weird in the z direction.

**Additional Context**

In the twitch stream: https://www.twitch.tv/videos/1712208885?t=1h58m22s @wolfenrain suggested introducing a voxel pixel ratio factor for these kind of cases.
<img width="232" alt="Screenshot 2023-01-20 at 21 36 59" src="https://user-images.githubusercontent.com/6442915/213779472-f7887d7e-de96-4328-85c2-0a144a73be22.png">

**Comment by wolfenrain** [comment]
I did some testing with the example of Sashimi and there it scales as expected

Seems something is wrong in the game itself and not the engine 🤔, will have to dig deeper into it to be sure

PS: the pixel/voxel ratio is for the game to allow the simulation to work correctly ✌🏻

**Comment by wolfenrain** [comment]
After some deeper investigations I found that the priority calculation was wrong, it already applies scaling but that should happen on realignment of the position.

Will draft a PR to fix it.
